removed endor/qcom/opensource/dataservices
fix [  0% 4/29014] target  C: librmnetctl ...ataservices/rmnetctl/src/librmnetctl.c
FAILED: /home/thanhdatpd/lineage/out/target/product/bicot/obj/SHARED_LIBRARIES/librmnetctl_intermediates/librmnetctl.o 
/bin/bash -c "PWD=/proc/self/cwd  prebuilts/clang/host/linux-x86/clang-4691093/bin/clang 	-I device/meizu/bicot/include -I vendor/qcom/opensource/dataservices/rmnetctl/src/../inc -I vendor/qcom/opensource/dataservices/rmnetctl/src -I vendor/qcom/opensource/dataservices/rmnetctl/src -I /home/thanhdatpd/lineage/out/target/product/bicot/obj/SHARED_LIBRARIES/librmnetctl_intermediates -I /home/thanhdatpd/lineage/out/target/product/bicot/gen/SHARED_LIBRARIES/librmnetctl_intermediates -I libnativehelper/include_jni \$(cat /home/thanhdatpd/lineage/out/target/product/bicot/obj/SHARED_LIBRARIES/librmnetctl_intermediates/import_includes)  -I system/core/include -I system/media/audio/include -I hardware/libhardware/include -I hardware/libhardware_legacy/include -I hardware/ril/include -I libnativehelper/include -I frameworks/native/include -I frameworks/native/opengl/include -I frameworks/av/include -isystem /home/thanhdatpd/lineage/out/target/product/bicot/obj/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm64 -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -c  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-expansion-to-defined -Wno-zero-as-null-pointer-constant -fdebug-prefix-map=\$PWD/= -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -march=armv8-a -mcpu=kryo -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin   -std=gnu99    -Wall -Werror -fPIC -D_USING_LIBCXX -DANDROID_STRICT   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-null-pointer-arithmetic -Wno-enum-compare -Wno-enum-compare-switch -MD -MF /home/thanhdatpd/lineage/out/target/product/bicot/obj/SHARED_LIBRARIES/librmnetctl_intermediates/librmnetctl.d -o /home/thanhdatpd/lineage/out/target/product/bicot/obj/SHARED_LIBRARIES/librmnetctl_intermediates/librmnetctl.o vendor/qcom/opensource/dataservices/rmnetctl/src/librmnetctl.c"
vendor/qcom/opensource/dataservices/rmnetctl/src/librmnetctl.c:55:10: fatal error: 'linux/rmnet_data.h' file not found
#include <linux/rmnet_data.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
[  0% 7/29014] //frameworks/native/ope...GL header-abi-dumper EGL/egl.cpp [arm]
ninja: build stopped: subcommand failed.
10:43:57 ninja failed with: exit status 1